Moving ha-utils to keepalived and some other changes

diff --git a/jobs/keepalived/templates/bin/post-start.erb b/jobs/keepalived/templates/bin/post-start.erb
--- a/jobs/keepalived/templates/bin/post-start.erb
+++ b/jobs/keepalived/templates/bin/post-start.erb
@@ -1,6 +1,6 @@
 #!/bin/bash
 	
-#set -e # exit immediately if a simple command exits with a non-zero status
+set -e # exit immediately if a simple command exits with a non-zero status
 set -u # report the usage of uninitialized variables
 # source properties file here.
 export IS_HA=<%= link("broker").p("ha_enabled") %>
@@ -63,3 +63,4 @@ if [[ "$iaas_name" == "gcp" && "$IS_HA" == "true" ]]; then
   echo "GCP Post-start script execution completed"
   exit $RETURN_CODE
 fi
+exit 0
