Changes for openstck ha: 1. Some function introduced for common code 2. Some restructure of codes 3. some improvements in logging

diff --git a/jobs/keepalived/templates/bin/utils/openstack/generate_token b/jobs/keepalived/templates/bin/utils/openstack/generate_token
--- a/jobs/keepalived/templates/bin/utils/openstack/generate_token
+++ b/jobs/keepalived/templates/bin/utils/openstack/generate_token
@@ -2,7 +2,6 @@
 #sourcing job properties to bring openstack credential in env variables
 # shellcheck disable=SC1091
 source /var/vcap/jobs/keepalived/bin/job_properties.sh
-jq=/var/vcap/packages/jq/bin/jq
 generate_body_for_token_req()
 {
  cat << EOF
@@ -38,20 +37,30 @@ generate_auth_token(){
         echo "$(date) [ERROR] - HTTP Error:  ${token_response}"
         exit ${RET}
     fi
-    OS_CATALOG=$(echo "${token_response}" | $jq -r .token.catalog[])
+    OS_CATALOG=$(echo "${token_response}" | ${JQ_CMD} -r .token.catalog[])
+    RET=$?
+    if [[ $RET -ne 0 ]] ; then
+        echo "$(date) [ERROR] - While parsing :  ${token_response} to get catalog ${OS_CATALOG}"
+        exit ${RET}
+    fi
     export OS_CATALOG
-    NETWORK_PUBLIC_URL="$(echo "${OS_CATALOG}" | $jq \
+    NETWORK_PUBLIC_URL="$(echo "${OS_CATALOG}" | ${JQ_CMD} \
         -r '. | select(.type=="network") | .endpoints[] | select(.interface=="public") | .url')"
+    RET=$?
+    if [[ $RET -ne 0 ]] ; then
+        echo "$(date) [ERROR] - While parsing : ${OS_CATALOG} to get network public url ${NETWORK_PUBLIC_URL}"
+        exit ${RET}
+    fi
     export NETWORK_PUBLIC_URL
     OS_TOKEN="$(curl --retry 2 -ski \
         -H "Content-Type: application/json" \
         -d "$(generate_body_for_token_req)" \
         "${OS_AUTH_URL}/auth/tokens" -X POST | awk '/X-Subject-Token/ {print $2}' )"
-    export OS_TOKEN
     RET=$?
     if [[ $RET -ne 0 ]] || [[ -z "${OS_TOKEN}" ]] ; then
-        echo "$(date) [ERROR] - HTTP Error or token not generated."
+        echo "$(date) [ERROR] - HTTP Error or token not generated: ${OS_TOKEN}"
         exit ${RET}
     fi
+    export OS_TOKEN
 }
 generate_auth_token
