Made bosh release self contained except aws-cli, some changes in HA scripts

diff --git a/packages/keepalived/packaging b/packages/keepalived/packaging
--- a/packages/keepalived/packaging
+++ b/packages/keepalived/packaging
@@ -2,8 +2,16 @@
 set -e
 set -u
 
-curl --progress http://keepalived.org/software/keepalived-1.2.15.tar.gz | tar xz
-cd keepalived-1.2.15/
+KEEPALIVED_VERSION="1.4.2"
+# Extracting keepalived package
+tar zxvf keepalived/keepalived-${KEEPALIVED_VERSION}.tar.gz
+
+if [[ $? != 0 ]] ; then
+  echo "Failed extracting python ${KEEPALIVED_VERSION}"
+  exit 1
+fi
+
+cd keepalived-${KEEPALIVED_VERSION}/
 
 #compile keepalive
 ./configure --prefix=${BOSH_INSTALL_TARGET}
diff --git a/packages/python/packaging b/packages/python/packaging
--- a/packages/python/packaging
+++ b/packages/python/packaging
@@ -1,7 +1,21 @@
-wget https://www.python.org/ftp/python/2.7.6/Python-2.7.6.tgz
+#!/bin/bash
+set -e
 
-tar zxf Python-2.7.6.tgz
+PYTHON_VERSION="2.7.6"
+# Extract python package
+echo "Extracting python ${PYTHON_VERSION}..."
+tar xpvf ${BOSH_COMPILE_TARGET}/python/Python-${PYTHON_VERSION}.tar.xz
+if [[ $? != 0 ]] ; then
+  echo "Failed extracting python ${PYTHON_VERSION}"
+  exit 1
+fi
 
-cd Python-2.7.6
+# Copy python package
+echo "Copying python ${PYTHON_VERSION}..."
+cp -a ${BOSH_COMPILE_TARGET}/Python-${PYTHON_VERSION}/* ${BOSH_INSTALL_TARGET}/
 
-./configure --prefix=${BOSH_INSTALL_TARGET} && make && make install
+echo "Installing python..."
+cd ${BOSH_INSTALL_TARGET}
+./configure --prefix=$BOSH_INSTALL_TARGET
+make
+make install
